<?php

namespace ContainerGxywoMN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5Xz1ebaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Xz1eba' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Xz1eba'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\DashboardController::addUser' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\DashboardController::adminDashboard' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\DashboardController::adminUsers' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\DashboardController::createUser' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\DashboardController::dashboardIndex' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\DashboardController::deleteUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\DashboardController::editUser' => ['privates', '.service_locator.H38vlv9', 'get_ServiceLocator_H38vlv9Service', true],
            'App\\Controller\\DashboardController::updateUser' => ['privates', '.service_locator.H38vlv9', 'get_ServiceLocator_H38vlv9Service', true],
            'App\\Controller\\DashboardController::usersAdd' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\SecurityController::forgotPassword' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\SecurityController::resetPassword' => ['privates', '.service_locator.KVWvkFB', 'get_ServiceLocator_KVWvkFBService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\DashboardController:addUser' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\DashboardController:adminDashboard' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\DashboardController:adminUsers' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\DashboardController:createUser' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\DashboardController:dashboardIndex' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\DashboardController:deleteUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\DashboardController:editUser' => ['privates', '.service_locator.H38vlv9', 'get_ServiceLocator_H38vlv9Service', true],
            'App\\Controller\\DashboardController:updateUser' => ['privates', '.service_locator.H38vlv9', 'get_ServiceLocator_H38vlv9Service', true],
            'App\\Controller\\DashboardController:usersAdd' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\SecurityController:forgotPassword' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\SecurityController:resetPassword' => ['privates', '.service_locator.KVWvkFB', 'get_ServiceLocator_KVWvkFBService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\DashboardController::addUser' => '?',
            'App\\Controller\\DashboardController::adminDashboard' => '?',
            'App\\Controller\\DashboardController::adminUsers' => '?',
            'App\\Controller\\DashboardController::createUser' => '?',
            'App\\Controller\\DashboardController::dashboardIndex' => '?',
            'App\\Controller\\DashboardController::deleteUser' => '?',
            'App\\Controller\\DashboardController::editUser' => '?',
            'App\\Controller\\DashboardController::updateUser' => '?',
            'App\\Controller\\DashboardController::usersAdd' => '?',
            'App\\Controller\\SecurityController::forgotPassword' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Controller\\SecurityController::resetPassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DashboardController:addUser' => '?',
            'App\\Controller\\DashboardController:adminDashboard' => '?',
            'App\\Controller\\DashboardController:adminUsers' => '?',
            'App\\Controller\\DashboardController:createUser' => '?',
            'App\\Controller\\DashboardController:dashboardIndex' => '?',
            'App\\Controller\\DashboardController:deleteUser' => '?',
            'App\\Controller\\DashboardController:editUser' => '?',
            'App\\Controller\\DashboardController:updateUser' => '?',
            'App\\Controller\\DashboardController:usersAdd' => '?',
            'App\\Controller\\SecurityController:forgotPassword' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'App\\Controller\\SecurityController:resetPassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
