<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXu1vbAe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXu1vbAe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXu1vbAe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXu1vbAe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXu1vbAe\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xu1vbAe',
    'container.build_id' => '2b4208b5',
    'container.build_time' => 1771806468,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXu1vbAe');
