<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxywoMN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxywoMN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxywoMN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxywoMN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGxywoMN\App_KernelDevDebugContainer([
    'container.build_hash' => 'GxywoMN',
    'container.build_id' => 'e8ab0d3c',
    'container.build_time' => 1770867527,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxywoMN');
