<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5xEBq5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5xEBq5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB5xEBq5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB5xEBq5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB5xEBq5\App_KernelDevDebugContainer([
    'container.build_hash' => 'B5xEBq5',
    'container.build_id' => '6f293658',
    'container.build_time' => 1771632470,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5xEBq5');
